services:
  - type: web
    plan: free
    name: Mdisk-download-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    repo: https://github.com/dktest2/Mdisk-download-bot.git      
    branch: main
    envVars:
      - key: TOKEN 
        sync: false
      - key: ID 
        sync: false
      - key: HASH 
        sync: false
    autoDeploy: false 
